package iban

var czechKnownBankCodes = map[uint16]string{
	100:  "Komerční banka, a.s.",
	300:  "ČSOB, a.s.",
	600:  "MONETA Money Bank, a.s.",
	710:  "Česká národní banka",
	800:  "Česká spořitelna, a.s.",
	2010: "Fio banka, a.s.",
	2020: "MUFG Bank (Europe) N.V. Prague B",
	2060: "Citfin, spořitelní d",
	2070: "TRINITY BANK a.s.",
	2100: "Hypoteční banka, a.s.",
	2200: "Peněžní dům, spořitelní d",
	2220: "Artesa, spořitelní d",
	2250: "Banka CREDITAS a.s.",
	2260: "NEY spořitelní d",
	2275: "Podnikatelská družstevní z",
	2600: "Citibank Europe plc, organizační s",
	2700: "UniCredit Bank Czech Republic and Slovakia, a.s.",
	3030: "Air Bank a. s.",
	3050: "BNP Paribas Personal Finance SA, odštěpný z",
	3060: "PKO BP S.A., Czech B",
	3500: "ING Bank N.V.",
	4000: "Max banka a.s.",
	4300: "Národní rozvojová banka, a.s. (dříve Českomoravská záruční a rozvojová banka, a.s.)",
	5500: "Raiffeisenbank a.s.",
	5800: "J&T Banka, a.s.",
	6000: "PPF banka a.s.",
	6100: "Raiffeisenbank a.s. (do 31. 12. 2021 Equa bank a.s.)",
	6200: "COMMERZBANK Aktiengesellschaft, pobočka P",
	6210: "mBank S.A., organizační s",
	6300: "BNP Paribas S.A., pobočka Česká r",
	6700: "Všeobecná úverová banka a.s., pobočka P",
	7910: "Deutsche Bank A.G. Filiale P",
	7950: "Raiffeisen stavební spořitelna a.s.",
	7960: "ČSOB Stavební spořitelna, a.s. (dříve Českomoravská stavební spořitelna a. s.)",
	7970: "Moneta Stavební spořitelna a.s.",
	7990: "Modrá pyramida stavební spořitelna, a.s.",
	8030: "Volksbank Raiffeisenbank Nordoberpfalz eG pobočka C",
	8040: "Oberbank AG pobočka Česká r",
	8060: "Stavební spořitelna České spořitelny, a.s.",
	8090: "Česká exportní banka, a.s.",
	8150: "HSBC Continental Europe, Czech R",
	8190: "Sparkasse Oberlausitz-N",
	8198: "FAS finance company s.r.o.",
	8199: "MoneyPolo Europe s.r.o.",
	8200: "PRIVAT BANK AG der Raiffeisenlandesbank Oberösterreich v České r",
	8220: "Payment Execution s.r.o.",
	8230: "ABAPAY s.r.o.",
	8240: "Družstevní záložna Kredit, v l",
	8250: "Bank of China (CEE) Ltd. Prague B",
	8255: "Bank of Communications Co., Ltd., Prague Branch odštěpný z",
	8265: "Industrial and Commercial Bank of China Limited, Prague Branch, odštěpný z",
	8270: "Fairplay Pay s.r.o.",
	8280: "B-Efekt a.s.",
	8293: "Mercurius partners s.r.o.",
	8299: "BESTPAY s.r.o.",
	8500: "Ferratum Bank p",
}
